Improvements
kse-ua/git-playground pull request #1
Opened 2022-11-27 16:41 UTC by kmirik999

2022-11-27 16:52 UTC, kmirik999 commented
merge

2022-12-04 21:17 UTC, tshemsedinov requested changes
Shame on you `if (exist == False):` equals to `if exist:`

2022-12-04 21:17 UTC, tshemsedinov commented on main.py
> +    exist = False
```suggestion
```

2022-12-04 21:17 UTC, tshemsedinov commented on main.py
> +            continue
```suggestion
        if guess in guesses:
            guessed += 1
            guesses.append(guess)
        else:
            print(f"Repeat input. That word is exist.")
            continue
```

2022-12-04 23:15 UTC, closed without merging